# Generated by Django 5.0 on 2023-12-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Действующий'), (False, 'Заблокирован')], default=False, verbose_name='Статус пользователя'),
        ),
    ]
