# Generated by Django 5.0 on 2023-12-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='debt_to_supplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='задолженность поставщику'),
        ),
    ]
