# Generated by Django 5.0 on 2023-12-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='наименование')),
                ('product_model', models.CharField(max_length=150, verbose_name='модель')),
                ('product_release', models.DateField(verbose_name='дата релиза')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('product_name',),
            },
        ),
    ]
